# Generated by Django 6.0.3 on 2026-03-30 19:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="clientes/"),
                ),
                ("site", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("carga_horaria", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Diretoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cargo", models.CharField(max_length=100)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="diretoria/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "valor_sugerido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="doacoes/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Esporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="esportes/"),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("data", models.DateField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="eventos/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Historia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("texto", models.TextField(blank=True, null=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="noticias/"),
                ),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Parceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("desconto", models.CharField(blank=True, max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="parceiros"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Socio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("numero_socio", models.CharField(max_length=50)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("rg", models.CharField(max_length=20)),
                ("senha", models.CharField(max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "status_pagamento",
                    models.CharField(
                        choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                        default="Inativo",
                        max_length=10,
                    ),
                ),
                (
                    "investimento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("foto", models.ImageField(blank=True, null=True, upload_to="fotos/")),
                (
                    "data_cadastro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
                ("jan", models.BooleanField(default=False)),
                ("fev", models.BooleanField(default=False)),
                ("mar", models.BooleanField(default=False)),
                ("abr", models.BooleanField(default=False)),
                ("mai", models.BooleanField(default=False)),
                ("jun", models.BooleanField(default=False)),
                ("jul", models.BooleanField(default=False)),
                ("ago", models.BooleanField(default=False)),
                ("set", models.BooleanField(default=False)),
                ("out", models.BooleanField(default=False)),
                ("nov", models.BooleanField(default=False)),
                ("dez", models.BooleanField(default=False)),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="socios.socio"
                    ),
                ),
            ],
        ),
    ]
