# Generated by Django 6.0.3 on 2026-03-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parceiro",
            name="desconto",
        ),
        migrations.AddField(
            model_name="parceiro",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="parceiro",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="parceiros/"),
        ),
        migrations.AlterField(
            model_name="parceiro",
            name="nome",
            field=models.CharField(max_length=200),
        ),
    ]
